# Generated by Django 6.0.2 on 2026-05-25 10:34

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate_per_unit', models.FloatField(default=8.56)),
                ('fixed_charge_per_kw', models.FloatField(default=400.0)),
                ('phase_1_rent', models.FloatField(default=10.0)),
                ('phase_3_rent', models.FloatField(default=25.0)),
                ('duty_percentage', models.FloatField(default=7.5)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Billing Settings',
                'verbose_name_plural': 'Billing Settings',
            },
        ),
        migrations.CreateModel(
            name='Meter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_number', models.CharField(max_length=50, unique=True)),
                ('meter_type', models.CharField(choices=[('10', 'Standard (10A)'), ('25', 'Enhanced (25A)')], default='10', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], default='active', max_length=20)),
                ('installation_date', models.DateField(auto_now_add=True)),
                ('deactivation_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'Meter',
                'verbose_name_plural': 'Meters',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(choices=[('admin', 'Administrator'), ('meter_reader', 'Meter Reader')], db_index=True, default='meter_reader', max_length=20)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'ordering': ['username'],
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='AdminNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('info', 'Info'), ('success', 'Success'), ('warning', 'Warning'), ('error', 'Error')], default='info', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bill_number', models.CharField(blank=True, max_length=50, unique=True)),
                ('units', models.FloatField(default=0)),
                ('rate_per_unit', models.FloatField(default=0)),
                ('fixed_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('energy_charges', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('duty_charge', models.FloatField(default=0)),
                ('regulatory_surcharge', models.FloatField(default=0)),
                ('meter_rent', models.FloatField(default=0)),
                ('arrears', models.FloatField(default=0)),
                ('late_payment_surcharge', models.FloatField(default=0)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('paid_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('issued', 'Issued'), ('paid', 'Paid'), ('overdue', 'Overdue'), ('cancelled', 'Cancelled')], db_index=True, default='draft', max_length=20)),
                ('is_locked', models.BooleanField(default=False)),
                ('locked_at', models.DateTimeField(blank=True, null=True)),
                ('created_source', models.CharField(choices=[('mobile_reader', 'Mobile Reader'), ('admin_manual', 'Admin Manual'), ('excel_import', 'Excel Import'), ('offline_sync', 'Offline Sync')], db_index=True, default='mobile_reader', max_length=20)),
                ('manual_override_reason', models.TextField(blank=True, null=True)),
                ('units_consumed_snapshot', models.FloatField(blank=True, null=True)),
                ('rate_snapshot', models.FloatField(blank=True, null=True)),
                ('total_amount_snapshot', models.FloatField(blank=True, null=True)),
                ('consumer_name_snapshot', models.CharField(blank=True, max_length=255, null=True)),
                ('meter_number_snapshot', models.CharField(blank=True, max_length=100, null=True)),
                ('bill_date', models.DateField(auto_now_add=True)),
                ('billing_period_start', models.DateField(blank=True, null=True)),
                ('billing_period_end', models.DateField(blank=True, null=True)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('transaction_id', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('locked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='locked_bills', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Bill',
                'verbose_name_plural': 'Bills',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('reading_submit', 'Reading Submitted'), ('bill_calculate', 'Bill Calculated'), ('bill_finalize', 'Bill Finalized'), ('payment_update', 'Payment Updated'), ('failed_mod', 'Failed Modification Attempt'), ('pdf_gen', 'PDF Generated')], db_index=True, max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('details', models.JSONField(default=dict)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
                ('bill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='billing.bill')),
            ],
            options={
                'verbose_name': 'Audit Log',
                'verbose_name_plural': 'Audit Logs',
                'ordering': ['-timestamp'],
            },
        ),
        migrations.CreateModel(
            name='Consumer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consumer_number', models.CharField(max_length=20, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('phone', models.CharField(blank=True, default='', max_length=20)),
                ('address', models.TextField(blank=True, default='')),
                ('post', models.CharField(blank=True, default='', max_length=100)),
                ('department', models.CharField(blank=True, default='', max_length=100)),
                ('meter_number', models.CharField(blank=True, max_length=50, null=True, unique=True)),
                ('connection_type', models.CharField(choices=[('single_phase', 'Single Phase'), ('three_phase', 'Three Phase')], default='single_phase', max_length=20)),
                ('load_kw', models.DecimalField(decimal_places=2, default=1.0, max_digits=10)),
                ('meter_type', models.CharField(choices=[('analog', 'Analog'), ('digital', 'Digital'), ('smart', 'Smart')], default='analog', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('disconnected', 'Disconnected')], db_index=True, default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consumer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Consumer',
                'verbose_name_plural': 'Consumers',
                'ordering': ['consumer_number'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='consumer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bills', to='billing.consumer'),
        ),
        migrations.CreateModel(
            name='ConsumerMeterAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('assignment_reason', models.CharField(choices=[('new_allocation', 'New Allocation'), ('quarter_shift', 'Quarter Shift'), ('temporary_overlap', 'Temporary Overlap'), ('meter_replacement', 'Meter Replacement')], default='new_allocation', max_length=50)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='billing.consumer')),
                ('meter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='billing.meter')),
            ],
            options={
                'verbose_name': 'Consumer Meter Assignment',
                'verbose_name_plural': 'Consumer Meter Assignments',
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='meter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bills', to='billing.meter'),
        ),
        migrations.CreateModel(
            name='MeterReading',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_reading', models.FloatField(default=0)),
                ('current_reading', models.FloatField(default=0)),
                ('units_consumed', models.FloatField(blank=True, default=0)),
                ('reading_date', models.DateField(blank=True, default=django.utils.timezone.now, null=True)),
                ('reading_time', models.TimeField(blank=True, default=django.utils.timezone.now, null=True)),
                ('meter_image', models.ImageField(blank=True, null=True, upload_to='meter_images/')),
                ('remarks', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_source', models.CharField(choices=[('mobile_reader', 'Mobile Reader'), ('admin_manual', 'Admin Manual'), ('excel_import', 'Excel Import'), ('offline_sync', 'Offline Sync')], db_index=True, default='mobile_reader', max_length=20)),
                ('manual_override_reason', models.TextField(blank=True, null=True)),
                ('consumer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.consumer')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_readings', to=settings.AUTH_USER_MODEL)),
                ('meter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='readings', to='billing.meter')),
            ],
            options={
                'verbose_name': 'Meter Reading',
                'verbose_name_plural': 'Meter Readings',
                'ordering': ['-reading_date'],
            },
        ),
        migrations.AddField(
            model_name='bill',
            name='meter_reading',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='billing.meterreading'),
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=50, unique=True)),
                ('amount', models.FloatField()),
                ('payment_method', models.CharField(choices=[('credit_card', 'Credit Card'), ('debit_card', 'Debit Card'), ('bank_transfer', 'Bank Transfer'), ('cash', 'Cash'), ('online', 'Online Payment')], max_length=50)),
                ('payment_date', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=20)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='billing.bill')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'ordering': ['-payment_date'],
            },
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.CheckConstraint(condition=models.Q(('connection_type__in', ['single_phase', 'three_phase'])), name='chk_consumer_connection_type'),
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.CheckConstraint(condition=models.Q(('meter_type__in', ['analog', 'digital', 'smart'])), name='chk_consumer_meter_type'),
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['active', 'inactive', 'disconnected'])), name='chk_consumer_status'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('current_reading__gte', models.F('previous_reading'))), name='reading_current_gte_previous'),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('units_consumed__gte', 0)), name='reading_units_gte_0'),
        ),
        migrations.AddConstraint(
            model_name='bill',
            constraint=models.CheckConstraint(condition=models.Q(('status__in', ['draft', 'issued', 'paid', 'overdue', 'cancelled'])), name='chk_bill_status'),
        ),
    ]
