# Generated by Django 6.0.2 on 2026-05-25 10:35

from django.db import migrations


def create_custom_ddl(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
-- Create indexes that Django didn't naturally generate
CREATE INDEX IF NOT EXISTS idx_meterreading_date ON billing_meterreading(reading_date);
CREATE INDEX IF NOT EXISTS idx_bill_date ON billing_bill(bill_date);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_consumer_updated_at BEFORE UPDATE ON billing_consumer
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bill_updated_at BEFORE UPDATE ON billing_bill
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
        """
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)

def reverse_custom_ddl(apps, schema_editor):
    if schema_editor.connection.vendor == 'postgresql':
        sql = """
DROP TRIGGER IF EXISTS update_bill_updated_at ON billing_bill;
DROP TRIGGER IF EXISTS update_consumer_updated_at ON billing_consumer;
DROP FUNCTION IF EXISTS update_updated_at_column();
DROP INDEX IF EXISTS idx_meterreading_date;
DROP INDEX IF EXISTS idx_bill_date;
        """
        with schema_editor.connection.cursor() as cursor:
            cursor.execute(sql)

class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_custom_ddl, reverse_custom_ddl)
    ]
