# Generated by Django 6.0.2 on 2026-02-21 09:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='bill_number',
            field=models.CharField(blank=True, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bill',
            name='fixed_charges',
            field=models.FloatField(default=125.0),
        ),
        migrations.AlterField(
            model_name='bill',
            name='rate_per_unit',
            field=models.FloatField(default=7.5),
        ),
    ]
