# Generated by Django 6.0.2 on 2026-02-24 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bill_bill_number_alter_bill_fixed_charges_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=200)),
            ],
        ),
    ]
