# Generated by Django 6.0.2 on 2026-06-16 23:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_custom_ddl'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='billing_type',
            field=models.CharField(choices=[('salary', 'Salary'), ('non_salary', 'Non-Salary')], default='salary', max_length=20),
        ),
        migrations.AddConstraint(
            model_name='consumer',
            constraint=models.CheckConstraint(condition=models.Q(('billing_type__in', ['salary', 'non_salary'])), name='chk_consumer_billing_type'),
        ),
    ]
