# Generated by Django 6.0.5 on 2026-05-18 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_bug39_add_consumer_number_snapshot'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bill',
            name='consumer_number_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddConstraint(
            model_name='meterreading',
            constraint=models.CheckConstraint(condition=models.Q(('current_reading__gte', models.F('previous_reading'))), name='reading_current_gte_previous'),
        ),
    ]
