# Generated by Django 6.0.5 on 2026-06-25 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_consumer_billing_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Administrator'), ('meter_reader', 'Meter Reader'), ('consumer', 'Consumer')], db_index=True, default='meter_reader', max_length=20),
        ),
    ]
