# Generated by Django 6.0.2 on 2026-07-27 19:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_consumer_role'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='consumer',
            name='chk_consumer_meter_type',
        ),
        migrations.RemoveField(
            model_name='consumer',
            name='meter_type',
        ),
    ]
