# Generated by Django 6.0.2 on 2026-07-31 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_consumer_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='billingsettings',
            name='lps_rate',
            field=models.DecimalField(decimal_places=2, default=1.5, help_text='Late Payment Surcharge rate in % applied per billing cycle on the total outstanding principal.', max_digits=5),
        ),
    ]
