# Generated by Django 6.0.2 on 2026-07-27 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_remove_consumer_meter_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='address_snapshot',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='connection_type_snapshot',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='department_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='load_kw_snapshot',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='post_snapshot',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
