# Generated by Django 6.0.2 on 2026-03-18 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_billingsettings'),
    ]

    operations = [
        migrations.AlterField(
            model_name='consumer',
            name='load_kw',
            field=models.FloatField(choices=[(1.0, '1 KW'), (2.0, '2 KW'), (3.0, '3 KW'), (4.0, '4 KW'), (5.0, '5 KW')], default=1.0),
        ),
    ]
