# Generated by Django 6.0.4 on 2026-04-22 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0006_alter_consumer_load_kw'),
    ]

    operations = [
        migrations.AddField(
            model_name='consumer',
            name='department',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='consumer',
            name='post',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
