#!/bin/bash

# This script opens 3 separate terminal windows using macOS native "open" command.

DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "--- Detecting Local Network IP ---"
# Get the first non-loopback IPv4 address
LOCAL_IP=$(ifconfig | grep "inet " | grep -v 127.0.0.1 | awk '{print $2}' | head -n 1)

if [ -n "$LOCAL_IP" ]; then
    echo "Found IP: $LOCAL_IP"
    echo "Updating eMeterApp/.env with current IP..."
    
    # Create or replace the .env file with the current IP
    cat > "$DIR/eMeterApp/.env" << EOF
# Auto-generated by START_PROJECT.sh
# Local backend configuration for eMeterApp
EXPO_PUBLIC_API_URL=http://$LOCAL_IP:8000
EOF
    echo "✅ eMeterApp/.env updated successfully."
else
    echo "⚠️ Warning: Could not detect local IP address. Using existing .env."
fi

echo "--- Cleaning up existing processes on ports 8000, 3000, 8081 ---"
lsof -ti:8000,3000,8081 | xargs kill -9 2>/dev/null || true

echo "--- Launching Backend (Django) ---"
open "$DIR/start_backend.command"

echo "--- Launching Frontend (React) ---"
open "$DIR/start_frontend.command"

echo "--- Launching Mobile App (Expo) ---"
open "$DIR/start_mobile.command"

echo "Done! All three services are launching in separate windows."

