#!/bin/bash
DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"

echo "=========================================================="
echo " Starting Public Internet Tunnel (Localtunnel)            "
echo "=========================================================="
echo "This tunnel allows your mobile app to connect to your Mac"
echo "from anywhere in the world (5G, Campus Wi-Fi, etc)."
echo ""

# Start localtunnel and pipe its output so we can capture the URL
npx localtunnel --port 8000 > /tmp/lt.log 2>&1 &
LT_PID=$!

echo "Waiting for tunnel to connect..."
sleep 3

# Extract the URL from the log
LT_URL=$(grep -o 'https://.*\.loca\.lt' /tmp/lt.log | head -1)

if [ -n "$LT_URL" ]; then
    echo "✅ Tunnel Connected!"
    echo "Public URL: $LT_URL"
    
    # Update the mobile app's .env file to use the public URL
    cat > "$DIR/eMeterApp/.env" << EOF
# Auto-generated by start_tunnel.command
# Public backend configuration for eMeterApp (Works anywhere)
EXPO_PUBLIC_API_URL=$LT_URL
EOF
    echo "✅ eMeterApp/.env updated with Public URL."
else
    echo "❌ Failed to connect to Localtunnel. Falling back to local IP."
    cat /tmp/lt.log
fi

echo ""
echo "Keep this window open to keep the tunnel alive."
echo "Press Ctrl+C to close the tunnel."

# Wait for the background process so the window stays open
wait $LT_PID
