"""
Django settings for electricity_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
# NOTE: DEBUG must be defined BEFORE SECRET_KEY to avoid NameError (FIX B-01)
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY')
if not SECRET_KEY:
    if not DEBUG:
        raise ValueError("DJANGO_SECRET_KEY environment variable is not set in production!")
    # Local dev fallback only (do not use in production)
    SECRET_KEY = 'django-insecure-local-dev-key-change-me'

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]
    # Auto-detect Render's external URL for ALLOWED_HOSTS (FIX REC-3)
    from urllib.parse import urlparse
    if _render_url := os.environ.get('RENDER_EXTERNAL_URL', ''):
        ALLOWED_HOSTS.append(urlparse(_render_url).hostname)



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

# ── Custom User Model ────────────────────────────────────────
# Must be set before any migration is run.
# All imports elsewhere must use get_user_model() or settings.AUTH_USER_MODEL
AUTH_USER_MODEL = 'billing.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Disable COOP header to allow access via IP addresses over HTTP without browser warnings in dev
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None



ROOT_URLCONF = 'electricity_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR.parent / 'energy-hub-ui' / 'dist',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electricity_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os


DB_PASSWORD = os.environ.get('DB_PASSWORD')
if not DB_PASSWORD and not os.environ.get('DATABASE_URL'):
    if not DEBUG:
        raise ValueError("DB_PASSWORD environment variable is not set in production (and DATABASE_URL is also missing)!")
    DB_PASSWORD = 'dev_password_change_me'  # safe local development fallback (configure your .env!)

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'emeter_db'),
        'USER': os.environ.get('DB_USER', 'emeter_user'),
        'PASSWORD': DB_PASSWORD,
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
        'CONN_MAX_AGE': 600 if os.environ.get('DB_ENGINE', 'django.db.backends.postgresql') == 'django.db.backends.postgresql' else 0,
    }
}

if DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    DATABASES['default']['OPTIONS'] = {
        'connect_timeout': 5,
    }

# FIX D-01 & D-03: Support DATABASE_URL from Neon with SSL
# Neon provides a single DATABASE_URL. If set, it overrides the individual DB_* vars.
import dj_database_url as _dj_db_url
if _db_url := os.environ.get('DATABASE_URL'):
    DATABASES['default'] = _dj_db_url.parse(_db_url, conn_max_age=600)
    # Neon requires SSL — enforce it regardless of URL params
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['sslmode'] = 'require'
    DATABASES['default']['OPTIONS']['connect_timeout'] = 5
elif not DEBUG and DATABASES['default']['ENGINE'] == 'django.db.backends.postgresql':
    # Fallback: individual vars with SSL enforced for production
    DATABASES['default'].setdefault('OPTIONS', {})
    DATABASES['default']['OPTIONS']['sslmode'] = 'require'

# Swap to SQLite3 for testing to avoid PostgreSQL permission errors
import sys
if 'test' in sys.argv:
    DATABASES['default'] = {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': ':memory:',
    }



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'Asia/Kolkata'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR.parent / 'energy-hub-ui' / 'dist',
]
# FIX B-05: STATICFILES_STORAGE deprecated in Django 4.2+; use STORAGES dict in Django 6.x
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# BUG-01 FIX: Single authoritative REST_FRAMEWORK block.
# Uses CsrfExemptSessionAuthentication so the /api/login/ endpoint works
# before a session exists, while all other endpoints stay CSRF-protected.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'rest_framework.authentication.SessionAuthentication',
    ],
}

# Security settings
if not DEBUG:
    # --- Production: Full HTTPS enforcement (Render provides HTTPS termination) ---
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
    # Render handles SSL termination at the edge; keep False to avoid redirect loops
    SECURE_SSL_REDIRECT = False
    # FIX B-03: Must be True in production with HTTPS
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    # FIX B-03: Enable HSTS in production
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
else:
    # --- Development: No HTTPS, but still enable HttpOnly protections ---
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False
    CSRF_COOKIE_SECURE = False

# CORS settings - Explicit whitelist only; never allow all origins
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
# Base always-allowed origins (localhost for web dev only)
_BASE_CORS = [
    "http://localhost:5173",
    "http://localhost:3000",
    "http://localhost:8080",
    "http://localhost:8081",
    "http://localhost:8082",
    "http://localhost:8083",
    "http://127.0.0.1:8080",
    "http://127.0.0.1:8081",
    "http://127.0.0.1:8082",
    "http://127.0.0.1:8083",
]

import os
# Runtime additions via env var (comma-separated), e.g. for ngrok or Cloudflare tunnel, or current LAN IP
_EXTRA_CORS = [
    o.strip()
    for o in os.environ.get('CORS_ALLOWED_ORIGINS_EXTRA', '').split(',')
    if o.strip()
]

CORS_ALLOWED_ORIGINS = _BASE_CORS + _EXTRA_CORS
CSRF_TRUSTED_ORIGINS = _BASE_CORS + _EXTRA_CORS

# Allow dynamic Localtunnel/ngrok domains in dev only
# In production, CORS is controlled exclusively via CORS_ALLOWED_ORIGINS_EXTRA env var
if DEBUG:
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https://.*\.loca\.lt$",          # Localtunnel dev tunnels
        r"^https://.*\.ngrok\.io$",          # ngrok dev tunnels
        r"^http://10\.\d{1,3}\.\d{1,3}\.\d{1,3}(:\d+)?$",      # Local LAN (dev only)
        r"^http://192\.168\.\d{1,3}\.\d{1,3}(:\d+)?$",          # Local LAN (dev only)
        r"^http://172\.(1[6-9]|2[0-9]|3[0-1])\.\d{1,3}\.\d{1,3}(:\d+)?$"  # Local LAN (dev only)
    ]
    CSRF_TRUSTED_ORIGINS.append("https://*.loca.lt")

    # Dynamically allow the dev machine's LAN IP (local VM/WiFi testing)
    import socket as _socket
    try:
        _s = _socket.socket(_socket.AF_INET, _socket.SOCK_DGRAM)
        _s.connect(("8.8.8.8", 80))
        _local_ip = _s.getsockname()[0]
        _s.close()
        CORS_ALLOWED_ORIGINS.extend([f"http://{_local_ip}:3000", f"http://{_local_ip}:5173"])
        CSRF_TRUSTED_ORIGINS.extend([f"http://{_local_ip}:3000", f"http://{_local_ip}:5173"])
    except Exception:
        pass
else:
    # Production: allow Vercel preview environments and production domains
    CORS_ALLOWED_ORIGIN_REGEXES = [
        r"^https://.*\.vercel\.app$",
    ]
    CSRF_TRUSTED_ORIGINS.append("https://*.vercel.app")

# CSRF cookie: NOT HttpOnly so SPA JS can read and attach it to X-CSRFToken header.
# This is the standard Django SPA pattern — do NOT set True.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SECURE is already set in the DEBUG block above.

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 28800
SESSION_COOKIE_SAMESITE = 'Lax'
# HttpOnly MUST be True — JS has no legitimate need to read the session cookie.
SESSION_COOKIE_HTTPONLY = True

# Twilio Settings (SMS or WhatsApp)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
# For SMS use: '+1234567890'. For WhatsApp use: 'whatsapp:+14155238886'
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')

# --- Logging System with Rotation ---
os.makedirs(BASE_DIR / 'logs', exist_ok=True)
LOGGING = {
    'version': 1,
    'disable_existing_loggers': False,
    'formatters': {
        'verbose': {
            'format': '{levelname} {asctime} {module} {process:d} {thread:d} {message}',
            'style': '{',
        },
        'simple': {
            'format': '{levelname} {message}',
            'style': '{',
        },
    },
    'handlers': {
        'console': {
            'class': 'logging.StreamHandler',
            'formatter': 'verbose',
        },
        'file': {
            'level': 'ERROR',
            'class': 'logging.handlers.RotatingFileHandler',
            'filename': BASE_DIR / 'logs' / 'emeter.log',
            'maxBytes': 1024 * 1024 * 10, # 10MB
            'backupCount': 5,
            'formatter': 'verbose',
        },
    },
    'root': {
        'handlers': ['console', 'file'],
        'level': 'WARNING',
    },
    'loggers': {
        'django': {
            'handlers': ['console', 'file'],
            'level': 'ERROR',
            'propagate': False,
        },
        'billing': {
            'handlers': ['console', 'file'],
            'level': 'INFO',
            'propagate': False,
        },
    },
}