"""
Django settings for electricity_system project.

Generated by 'django-admin startproject' using Django 6.0.2.

For more information on this file, see
https://docs.djangoproject.com/en/6.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/6.0/ref/settings/
"""

import os
from pathlib import Path
from dotenv import load_dotenv

# Load environment variables from .env file
load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/6.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get('DJANGO_SECRET_KEY', 'django-insecure-s(++$8^mg#8qqq%oua0yv#h+h3$7ftz1(i=mhi#md)k*d4b4y4')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = os.environ.get('DEBUG', 'True') == 'True'

if DEBUG:
    ALLOWED_HOSTS = ["*"]
else:
    ALLOWED_HOSTS = [host.strip() for host in os.environ.get('ALLOWED_HOSTS', '').split(',') if host.strip()]
    # '127.0.0.1',
    # 'localhost',
    # '10.215.227.32',
    # '10.86.158.33',
    # '10.86.112.32',
    # '10.91.159.32',
    # '10.131.109.32',



# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'billing',
    'rest_framework',
    'rest_framework.authtoken',
    'corsheaders',
]

# ── Custom User Model ────────────────────────────────────────
# Must be set before any migration is run.
# All imports elsewhere must use get_user_model() or settings.AUTH_USER_MODEL
AUTH_USER_MODEL = 'billing.User'

MIDDLEWARE = [
    'corsheaders.middleware.CorsMiddleware',
    'django.middleware.security.SecurityMiddleware',
    'whitenoise.middleware.WhiteNoiseMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

if DEBUG:
    # Disable COOP header to allow access via IP addresses over HTTP without browser warnings in dev
    SECURE_CROSS_ORIGIN_OPENER_POLICY = None



ROOT_URLCONF = 'electricity_system.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [
            BASE_DIR / 'templates',
            BASE_DIR.parent / 'energy-hub-ui' / 'build',
        ],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'electricity_system.wsgi.application'


# Database
# https://docs.djangoproject.com/en/6.0/ref/settings/#databases

import os


DB_PASSWORD = os.environ.get('DB_PASSWORD')
if not DB_PASSWORD:
    if not DEBUG:
        raise ValueError("DB_PASSWORD environment variable is not set in production!")
    DB_PASSWORD = 'anas167'  # safe local development fallback

DATABASES = {
    'default': {
        'ENGINE': os.environ.get('DB_ENGINE', 'django.db.backends.postgresql'),
        'NAME': os.environ.get('DB_NAME', 'emeter_db'),
        'USER': os.environ.get('DB_USER', 'emeter_user'),
        'PASSWORD': DB_PASSWORD,
        'HOST': os.environ.get('DB_HOST', 'localhost'),
        'PORT': os.environ.get('DB_PORT', '5432'),
    }
}



# Password validation
# https://docs.djangoproject.com/en/6.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/6.0/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/6.0/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = BASE_DIR / 'staticfiles'
STATICFILES_DIRS = [
    BASE_DIR / 'static',
    BASE_DIR.parent / 'energy-hub-ui' / 'dist',
]
STATICFILES_STORAGE = 'whitenoise.storage.CompressedManifestStaticFilesStorage'

# Media files
MEDIA_URL = '/media/'
MEDIA_ROOT = BASE_DIR / 'media'

# Default primary key field type
# https://docs.djangoproject.com/en/6.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
# SESSION_ENGINE = 'django.contrib.sessions.backends.signed_cookies'

# BUG-01 FIX: Single authoritative REST_FRAMEWORK block.
# Uses CsrfExemptSessionAuthentication so the /api/login/ endpoint works
# before a session exists, while all other endpoints stay CSRF-protected.
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework.authentication.TokenAuthentication',
        'electricity_system.authentication.CsrfExemptSessionAuthentication',
    ],
}

# Security settings
if not DEBUG:
    # --- Production: Full HTTPS enforcement ---
    SECURE_SSL_REDIRECT = True
    SESSION_COOKIE_SECURE = True
    CSRF_COOKIE_SECURE = True
    SECURE_BROWSER_XSS_FILTER = True
    SECURE_CONTENT_TYPE_NOSNIFF = True
    X_FRAME_OPTIONS = 'DENY'
    SECURE_HSTS_SECONDS = 31536000
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
else:
    # --- Development: No HTTPS, but still enable HttpOnly protections ---
    SECURE_SSL_REDIRECT = False
    SESSION_COOKIE_SECURE = False  # Can't be True without HTTPS locally
    CSRF_COOKIE_SECURE = False     # Same reason

# CORS settings - Explicit whitelist only; never allow all origins
CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",
    "http://localhost:8082",
    "http://localhost:8080",
    "http://localhost:3000",
    # Current machine IP
    "http://10.11.53.13:3000",
    "http://10.11.53.13:8000",
    "http://10.11.53.13:8081",
    "http://10.11.53.13:8082",
    # Previous / New IPs
    "http://10.215.227.32:3000",
    "http://10.215.227.32:8000",
    "http://10.215.227.32:8081",
    "http://10.215.227.32:8082",
    "http://10.86.158.33:8000",
    "http://10.86.158.33:8081",
]

CSRF_TRUSTED_ORIGINS = [
    'http://localhost:5173',
    'http://localhost:3000',
    'http://localhost:8080',
    'http://127.0.0.1:8080',
    'http://localhost:8081',
    'http://127.0.0.1:8081',
    'http://localhost:8082',
    'http://127.0.0.1:8082',
    'http://localhost:8083',
    'http://127.0.0.1:8083',
    # Current machine IP
    'http://10.11.53.13:3000',
    'http://10.11.53.13:8000',
    'http://10.11.53.13:8081',
    'http://10.11.53.13:8082',
    # Previous / New IPs (kept for reference)
    'http://10.131.109.32:8083',
    'http://10.86.112.32:8000',
    'http://10.91.159.32:8000',
    'http://10.86.158.33:8000',
    'http://10.86.158.33:8081',
    'http://10.215.227.32:3000',
    'http://10.215.227.32:8000',
    'http://10.215.227.32:8081',
    'http://10.215.227.32:8082',
]

# CSRF cookie: NOT HttpOnly so SPA JS can read and attach it to X-CSRFToken header.
# This is the standard Django SPA pattern — do NOT set True.
CSRF_COOKIE_HTTPONLY = False
CSRF_COOKIE_SAMESITE = 'Lax'
# CSRF_COOKIE_SECURE is already set in the DEBUG block above.

SESSION_COOKIE_DOMAIN = None
SESSION_COOKIE_AGE = 28800
SESSION_COOKIE_SAMESITE = 'Lax'
# HttpOnly MUST be True — JS has no legitimate need to read the session cookie.
SESSION_COOKIE_HTTPONLY = True

# Twilio Settings (SMS or WhatsApp)
TWILIO_ACCOUNT_SID = os.environ.get('TWILIO_ACCOUNT_SID', '')
TWILIO_AUTH_TOKEN = os.environ.get('TWILIO_AUTH_TOKEN', '')
# For SMS use: '+1234567890'. For WhatsApp use: 'whatsapp:+14155238886'
TWILIO_PHONE_NUMBER = os.environ.get('TWILIO_PHONE_NUMBER', '')
TWILIO_WHATSAPP_FROM = os.environ.get('TWILIO_WHATSAPP_FROM', 'whatsapp:+14155238886')