BEGIN;
--
-- Create model BillingSettings
--
CREATE TABLE "billing_billingsettings" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "rate_per_unit" double precision NOT NULL, "fixed_charge_per_kw" double precision NOT NULL, "phase_1_rent" double precision NOT NULL, "phase_3_rent" double precision NOT NULL, "duty_percentage" double precision NOT NULL, "updated_at" timestamp with time zone NOT NULL);
--
-- Create model Meter
--
CREATE TABLE "billing_meter" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "meter_number" varchar(50) NOT NULL UNIQUE, "meter_type" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "installation_date" date NOT NULL, "deactivation_date" date NULL, "is_active" boolean NOT NULL);
--
-- Create model User
--
CREATE TABLE "billing_user" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "password" varchar(128) NOT NULL, "last_login" timestamp with time zone NULL, "is_superuser" boolean NOT NULL, "username" varchar(150) NOT NULL UNIQUE, "first_name" varchar(150) NOT NULL, "last_name" varchar(150) NOT NULL, "email" varchar(254) NOT NULL, "is_staff" boolean NOT NULL, "is_active" boolean NOT NULL, "date_joined" timestamp with time zone NOT NULL, "role" varchar(20) NOT NULL);
CREATE TABLE "billing_user_groups" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "group_id" integer NOT NULL);
CREATE TABLE "billing_user_user_permissions" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "user_id" bigint NOT NULL, "permission_id" integer NOT NULL);
--
-- Create model AdminNotification
--
CREATE TABLE "billing_adminnotification" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "title" varchar(200) NOT NULL, "message" text NOT NULL, "notification_type" varchar(20) NOT NULL, "is_read" boolean NOT NULL, "created_at" timestamp with time zone NOT NULL, "user_id" bigint NULL);
--
-- Create model Bill
--
CREATE TABLE "billing_bill" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "bill_number" varchar(50) NOT NULL UNIQUE, "units" double precision NOT NULL, "rate_per_unit" double precision NOT NULL, "fixed_charges" numeric(10, 2) NOT NULL, "energy_charges" numeric(10, 2) NOT NULL, "duty_charge" double precision NOT NULL, "regulatory_surcharge" double precision NOT NULL, "meter_rent" double precision NOT NULL, "arrears" double precision NOT NULL, "late_payment_surcharge" double precision NOT NULL, "total_amount" numeric(10, 2) NOT NULL, "paid_amount" numeric(10, 2) NOT NULL, "status" varchar(20) NOT NULL, "is_locked" boolean NOT NULL, "locked_at" timestamp with time zone NULL, "created_source" varchar(20) NOT NULL, "manual_override_reason" text NULL, "units_consumed_snapshot" double precision NULL, "rate_snapshot" double precision NULL, "total_amount_snapshot" double precision NULL, "consumer_name_snapshot" varchar(255) NULL, "meter_number_snapshot" varchar(100) NULL, "bill_date" date NOT NULL, "billing_period_start" date NULL, "billing_period_end" date NULL, "due_date" date NULL, "payment_date" date NULL, "transaction_id" varchar(50) NOT NULL, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "locked_by_id" bigint NULL);
--
-- Create model AuditLog
--
CREATE TABLE "billing_auditlog" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "action" varchar(50) NOT NULL, "timestamp" timestamp with time zone NOT NULL, "details" jsonb NOT NULL, "ip_address" inet NULL, "user_id" bigint NULL, "bill_id" bigint NULL);
--
-- Create model Consumer
--
CREATE TABLE "billing_consumer" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "consumer_number" varchar(20) NOT NULL UNIQUE, "name" varchar(100) NOT NULL, "email" varchar(254) NULL UNIQUE, "phone" varchar(20) NOT NULL, "address" text NOT NULL, "post" varchar(100) NOT NULL, "department" varchar(100) NOT NULL, "meter_number" varchar(50) NULL UNIQUE, "connection_type" varchar(20) NOT NULL, "load_kw" numeric(10, 2) NOT NULL, "meter_type" varchar(20) NOT NULL, "status" varchar(20) NOT NULL, "created_at" timestamp with time zone NULL, "updated_at" timestamp with time zone NULL, "user_id" bigint NULL UNIQUE);
--
-- Add field consumer to bill
--
ALTER TABLE "billing_bill" ADD COLUMN "consumer_id" bigint NOT NULL CONSTRAINT "billing_bill_consumer_id_dc837f03_fk_billing_consumer_id" REFERENCES "billing_consumer"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "billing_bill_consumer_id_dc837f03_fk_billing_consumer_id" IMMEDIATE;
--
-- Create model ConsumerMeterAssignment
--
CREATE TABLE "billing_consumermeterassignment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "start_date" date NOT NULL, "end_date" date NULL, "is_active" boolean NOT NULL, "assignment_reason" varchar(50) NOT NULL, "consumer_id" bigint NOT NULL, "meter_id" bigint NOT NULL);
--
-- Add field meter to bill
--
ALTER TABLE "billing_bill" ADD COLUMN "meter_id" bigint NULL CONSTRAINT "billing_bill_meter_id_37822aac_fk_billing_meter_id" REFERENCES "billing_meter"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "billing_bill_meter_id_37822aac_fk_billing_meter_id" IMMEDIATE;
--
-- Create model MeterReading
--
CREATE TABLE "billing_meterreading" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "previous_reading" double precision NOT NULL, "current_reading" double precision NOT NULL, "units_consumed" double precision NOT NULL, "reading_date" date NULL, "reading_time" time NULL, "meter_image" varchar(100) NULL, "remarks" text NOT NULL, "created_at" timestamp with time zone NULL, "created_source" varchar(20) NOT NULL, "manual_override_reason" text NULL, "consumer_id" bigint NOT NULL, "created_by_id" bigint NULL, "meter_id" bigint NULL);
--
-- Add field meter_reading to bill
--
ALTER TABLE "billing_bill" ADD COLUMN "meter_reading_id" bigint NULL CONSTRAINT "billing_bill_meter_reading_id_73dc749c_fk_billing_m" REFERENCES "billing_meterreading"("id") DEFERRABLE INITIALLY DEFERRED; SET CONSTRAINTS "billing_bill_meter_reading_id_73dc749c_fk_billing_m" IMMEDIATE;
--
-- Create model Payment
--
CREATE TABLE "billing_payment" ("id" bigint NOT NULL PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, "transaction_id" varchar(50) NOT NULL UNIQUE, "amount" double precision NOT NULL, "payment_method" varchar(50) NOT NULL, "payment_date" timestamp with time zone NOT NULL, "status" varchar(20) NOT NULL, "bill_id" bigint NOT NULL);
--
-- Create constraint chk_consumer_connection_type on model consumer
--
ALTER TABLE "billing_consumer" ADD CONSTRAINT "chk_consumer_connection_type" CHECK ("connection_type" IN ('single_phase', 'three_phase'));
--
-- Create constraint chk_consumer_meter_type on model consumer
--
ALTER TABLE "billing_consumer" ADD CONSTRAINT "chk_consumer_meter_type" CHECK ("meter_type" IN ('analog', 'digital', 'smart'));
--
-- Create constraint chk_consumer_status on model consumer
--
ALTER TABLE "billing_consumer" ADD CONSTRAINT "chk_consumer_status" CHECK ("status" IN ('active', 'inactive', 'disconnected'));
--
-- Create constraint reading_current_gte_previous on model meterreading
--
ALTER TABLE "billing_meterreading" ADD CONSTRAINT "reading_current_gte_previous" CHECK ("current_reading" >= ("previous_reading"));
--
-- Create constraint reading_units_gte_0 on model meterreading
--
ALTER TABLE "billing_meterreading" ADD CONSTRAINT "reading_units_gte_0" CHECK ("units_consumed" >= 0.0);
--
-- Create constraint chk_bill_status on model bill
--
ALTER TABLE "billing_bill" ADD CONSTRAINT "chk_bill_status" CHECK ("status" IN ('draft', 'issued', 'paid', 'overdue', 'cancelled'));
CREATE INDEX "billing_meter_meter_number_2a77abaa_like" ON "billing_meter" ("meter_number" varchar_pattern_ops);
CREATE INDEX "billing_user_username_59ec0753_like" ON "billing_user" ("username" varchar_pattern_ops);
CREATE INDEX "billing_user_role_b97a7814" ON "billing_user" ("role");
CREATE INDEX "billing_user_role_b97a7814_like" ON "billing_user" ("role" varchar_pattern_ops);
ALTER TABLE "billing_user_groups" ADD CONSTRAINT "billing_user_groups_user_id_group_id_af6b9d11_uniq" UNIQUE ("user_id", "group_id");
ALTER TABLE "billing_user_groups" ADD CONSTRAINT "billing_user_groups_user_id_4385cb5c_fk_billing_user_id" FOREIGN KEY ("user_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_user_groups" ADD CONSTRAINT "billing_user_groups_group_id_2b1dc023_fk_auth_group_id" FOREIGN KEY ("group_id") REFERENCES "auth_group" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_user_groups_user_id_4385cb5c" ON "billing_user_groups" ("user_id");
CREATE INDEX "billing_user_groups_group_id_2b1dc023" ON "billing_user_groups" ("group_id");
ALTER TABLE "billing_user_user_permissions" ADD CONSTRAINT "billing_user_user_permis_user_id_permission_id_78bf0dc2_uniq" UNIQUE ("user_id", "permission_id");
ALTER TABLE "billing_user_user_permissions" ADD CONSTRAINT "billing_user_user_pe_user_id_65bb214f_fk_billing_u" FOREIGN KEY ("user_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_user_user_permissions" ADD CONSTRAINT "billing_user_user_pe_permission_id_0e45bb97_fk_auth_perm" FOREIGN KEY ("permission_id") REFERENCES "auth_permission" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_user_user_permissions_user_id_65bb214f" ON "billing_user_user_permissions" ("user_id");
CREATE INDEX "billing_user_user_permissions_permission_id_0e45bb97" ON "billing_user_user_permissions" ("permission_id");
ALTER TABLE "billing_adminnotification" ADD CONSTRAINT "billing_adminnotification_user_id_630ec85b_fk_billing_user_id" FOREIGN KEY ("user_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_adminnotification_user_id_630ec85b" ON "billing_adminnotification" ("user_id");
ALTER TABLE "billing_bill" ADD CONSTRAINT "billing_bill_locked_by_id_89e734b1_fk_billing_user_id" FOREIGN KEY ("locked_by_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_bill_bill_number_3e97e2ab_like" ON "billing_bill" ("bill_number" varchar_pattern_ops);
CREATE INDEX "billing_bill_status_453e8075" ON "billing_bill" ("status");
CREATE INDEX "billing_bill_status_453e8075_like" ON "billing_bill" ("status" varchar_pattern_ops);
CREATE INDEX "billing_bill_created_source_aadc31de" ON "billing_bill" ("created_source");
CREATE INDEX "billing_bill_created_source_aadc31de_like" ON "billing_bill" ("created_source" varchar_pattern_ops);
CREATE INDEX "billing_bill_locked_by_id_89e734b1" ON "billing_bill" ("locked_by_id");
ALTER TABLE "billing_auditlog" ADD CONSTRAINT "billing_auditlog_user_id_c9dbdeb4_fk_billing_user_id" FOREIGN KEY ("user_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_auditlog" ADD CONSTRAINT "billing_auditlog_bill_id_7fcf5365_fk_billing_bill_id" FOREIGN KEY ("bill_id") REFERENCES "billing_bill" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_auditlog_action_c17c0f66" ON "billing_auditlog" ("action");
CREATE INDEX "billing_auditlog_action_c17c0f66_like" ON "billing_auditlog" ("action" varchar_pattern_ops);
CREATE INDEX "billing_auditlog_timestamp_203d8a89" ON "billing_auditlog" ("timestamp");
CREATE INDEX "billing_auditlog_user_id_c9dbdeb4" ON "billing_auditlog" ("user_id");
CREATE INDEX "billing_auditlog_bill_id_7fcf5365" ON "billing_auditlog" ("bill_id");
ALTER TABLE "billing_consumer" ADD CONSTRAINT "billing_consumer_user_id_f453bf51_fk_billing_user_id" FOREIGN KEY ("user_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_consumer_consumer_number_0d9e5101_like" ON "billing_consumer" ("consumer_number" varchar_pattern_ops);
CREATE INDEX "billing_consumer_email_199bddcb_like" ON "billing_consumer" ("email" varchar_pattern_ops);
CREATE INDEX "billing_consumer_meter_number_3c04d122_like" ON "billing_consumer" ("meter_number" varchar_pattern_ops);
CREATE INDEX "billing_consumer_status_26dc7c48" ON "billing_consumer" ("status");
CREATE INDEX "billing_consumer_status_26dc7c48_like" ON "billing_consumer" ("status" varchar_pattern_ops);
CREATE INDEX "billing_bill_consumer_id_dc837f03" ON "billing_bill" ("consumer_id");
ALTER TABLE "billing_consumermeterassignment" ADD CONSTRAINT "billing_consumermete_consumer_id_9c240d42_fk_billing_c" FOREIGN KEY ("consumer_id") REFERENCES "billing_consumer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_consumermeterassignment" ADD CONSTRAINT "billing_consumermete_meter_id_d27e06a9_fk_billing_m" FOREIGN KEY ("meter_id") REFERENCES "billing_meter" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_consumermeterassignment_consumer_id_9c240d42" ON "billing_consumermeterassignment" ("consumer_id");
CREATE INDEX "billing_consumermeterassignment_meter_id_d27e06a9" ON "billing_consumermeterassignment" ("meter_id");
CREATE INDEX "billing_bill_meter_id_37822aac" ON "billing_bill" ("meter_id");
ALTER TABLE "billing_meterreading" ADD CONSTRAINT "billing_meterreading_consumer_id_c3d40dba_fk_billing_c" FOREIGN KEY ("consumer_id") REFERENCES "billing_consumer" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_meterreading" ADD CONSTRAINT "billing_meterreading_created_by_id_bb634ad4_fk_billing_user_id" FOREIGN KEY ("created_by_id") REFERENCES "billing_user" ("id") DEFERRABLE INITIALLY DEFERRED;
ALTER TABLE "billing_meterreading" ADD CONSTRAINT "billing_meterreading_meter_id_c142d9ae_fk_billing_meter_id" FOREIGN KEY ("meter_id") REFERENCES "billing_meter" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_meterreading_created_source_d0ec9e14" ON "billing_meterreading" ("created_source");
CREATE INDEX "billing_meterreading_created_source_d0ec9e14_like" ON "billing_meterreading" ("created_source" varchar_pattern_ops);
CREATE INDEX "billing_meterreading_consumer_id_c3d40dba" ON "billing_meterreading" ("consumer_id");
CREATE INDEX "billing_meterreading_created_by_id_bb634ad4" ON "billing_meterreading" ("created_by_id");
CREATE INDEX "billing_meterreading_meter_id_c142d9ae" ON "billing_meterreading" ("meter_id");
CREATE INDEX "billing_bill_meter_reading_id_73dc749c" ON "billing_bill" ("meter_reading_id");
ALTER TABLE "billing_payment" ADD CONSTRAINT "billing_payment_bill_id_2458d3c3_fk_billing_bill_id" FOREIGN KEY ("bill_id") REFERENCES "billing_bill" ("id") DEFERRABLE INITIALLY DEFERRED;
CREATE INDEX "billing_payment_transaction_id_010da732_like" ON "billing_payment" ("transaction_id" varchar_pattern_ops);
CREATE INDEX "billing_payment_bill_id_2458d3c3" ON "billing_payment" ("bill_id");
COMMIT;
BEGIN;
--
-- Raw SQL operation
--

-- Create indexes that Django didn't naturally generate
CREATE INDEX IF NOT EXISTS idx_meterreading_date ON billing_meterreading(reading_date);
CREATE INDEX IF NOT EXISTS idx_bill_date ON billing_bill(bill_date);

-- Create updated_at trigger
CREATE OR REPLACE FUNCTION update_updated_at_column()
RETURNS TRIGGER AS $$
BEGIN
    NEW.updated_at = CURRENT_TIMESTAMP;
    RETURN NEW;
END;
$$ language 'plpgsql';

CREATE TRIGGER update_consumer_updated_at BEFORE UPDATE ON billing_consumer
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();

CREATE TRIGGER update_bill_updated_at BEFORE UPDATE ON billing_bill
    FOR EACH ROW EXECUTE FUNCTION update_updated_at_column();
            
COMMIT;
